version: '2'
services:
  hexletcorrection:
    image: hexletcorrection
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=dev,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://hexletcorrection-postgresql:5432/hexletCorrection'
      - JHIPSTER_SLEEP=15
    ports:
      - '8080:8080'
  hexletcorrection-postgresql:
    image: 'postgres:12.1'
    environment:
      - POSTGRES_USER=hexletCorrection
      - POSTGRES_PASSWORD=
