spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/typo-reporter
    username: developer
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        use_sql_comments: true
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    web: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    io.hexlet.typoreporter: DEBUG
