version: '3'
services:
  typo-reporter-db-postgresql:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=typo-reporter
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
